[package]
name = "sga-unpacker"
version.workspace = true
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Cli for sga crate"

[dependencies]
sga = { version = "0.1.0", path = "../sga" }
relic-chunky = { version = "0.1.0", path = "../relic-chunky" }

clap = { workspace = true }
anyhow = { workspace = true }
