[package]
name = "relic-chunky"
description = "Read and write Relic Chunky formats: reflection .bin/.rdo, RGD game data, and rrtex textures"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[dependencies]
byteorder = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
quick-xml = { workspace = true }
anyhow.workspace = true
flate2 = { workspace = true }
png = { workspace = true }
intel_tex_2 = { workspace = true }
binrw = "0.15.2"

[dev-dependencies]
image_dds = "0.7"
